apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vibe-01-vcf9
  name: vibe-01-vcf9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vibe-01-vcf9
  strategy: {}
  template:
    metadata:
      labels:
        app: vibe-01-vcf9
    spec:
      containers:
      - image: jumpboxacademy/vibe-01-vcf9
        name: vibe-01-vcf9
        ports:
        - containerPort: 80
        resources: {}
status: {}
