apiVersion: v1
kind: Service
metadata:
  labels:
    app: vibe-01
  name: vibe-01
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: vibe-01
  type: LoadBalancer
status:
  loadBalancer: {}
