apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibe-01-vcf9
spec:
  template:
    spec:
      containers:
      - name: vibe-01-vcf9
        securityContext:
          privileged: true
          runAsNonRoot: false
          runAsUser: 0
          seccompProfile:
            type: Unconfined
          # allowPrivilegeEscalation: false
          # capabilities:
          #   drop:
          #   - ALL
          # runAsNonRoot: true
          # runAsUser: 1000
          # seccompProfile:
          #   type: RuntimeDefault