apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibe-01
spec:
  template:
    spec:
      containers:
      - name: vibe-01 
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault